idf_component_register(
    SRCS
        "lvgl_ui.c"
        "i2c_oled_example_main.cpp"
        "watchdog_util.c"
        "sensor_data.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        kiwi2c
        ads1115_cxx
        sht41
        esp_driver_i2c
        esp_lcd
        esp_timer
        esp_gdbstub
)
